# Generated by Django 4.0 on 2021-12-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restasite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Цена'),
        ),
    ]
