# Generated by Django 4.0 on 2021-12-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restasite', '0002_alter_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.CharField(choices=[('Main', 'Основное блюдо'), ('Drink', 'Напитки'), ('Other', 'Дополнительно')], default='Main', max_length=10, verbose_name='Тип'),
        ),
    ]
