# Generated by Django 4.0 on 2021-12-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restasite', '0005_alter_menuitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='Цена'),
        ),
    ]
